### PR TITLE
set version to 4.00

### PR DESCRIPTION
**Pull request by wsu-cb**
Start preparing for beta release.

### CODE REVIEW

**Comment by wsu-cb** [comment]
Should IDS_URL_CB_WEBSITE be changed to https://github.com/CyberBoardPBEM/cbwindows/releases as part of preparing for the release?

**Comment by DLLarson** [comment]
Hi Bill,

>Should IDS_URL_CB_WEBSITE be changed to https://github.com/CyberBoardPBEM/cbwindows/releases as part of preparing for the release?

I would say add a new IDS for "Latest Cyberboard Releases..." that points to the CB GitHub release area. The `IDS_URL_CB_WEBSITE` points to the website in our GitHub repo `cbweb`. That website ultimately needs to be updated with 4.0 information, links, etc... It's good to have a regular website where folks can learn about the program in a more narrative/graphical form.

One day we may even get the gumption to create an installer! Perhaps a person with installer chops will volunteer in the future once they get a taste of the newer program.

-Dale

**Comment by wsu-cb** [comment]
> I would say add a new IDS for "Latest Cyberboard Releases..." that points to the CB GitHub release area. The `IDS_URL_CB_WEBSITE` points to the website in our GitHub repo `cbweb`. That website ultimately needs to be updated with 4.0 information, links, etc... It's good to have a regular website where folks can learn about the program in a more narrative/graphical form.

That lack of 4.0 information is why I was suggesting changing the link.

**Comment by DLLarson** [comment]
>That lack of 4.0 information is why I was suggesting changing the link.

It does need to be updated. Probably when v4.0 goes official.

If I can't find/get Pokke to do it I guess I'll do it but I don't want the site to gone though.

It's been the only face of CB prior to GitHub. The fellow (aka site Brainiac) who used to host the site sold his web hosting business so I moved the site's web files to GitHub. Unfortunately in the shipping version of CB the old links are broken. However, strangely the web site's hit counter is still working!

-Dale

**Comment by wsu-cb** [comment]
Dale,
In (some?) previous pre-releases, there was an expiration date built into CB.  Do you want to do that again, or can we leave that out now?

**Comment by DLLarson** [comment]
>In (some?) previous pre-releases, there was an expiration date built into CB. 
>Do you want to do that again, or can we leave that out now?

Let's not do that. In those days the likelihood of a busted version hanging around was high given the internet wasn't much of a thing. The only way I could get them to upgrade was force the issue.

Right now people can literally find the source code and remove the blocking code with little difficulty. I think a better approach these days would be to simply remind them of new releases when detected in the release area and refer them there. Having a history of releases always available should also make upgrading less "scary."

-Dale

**Review by DLLarson — APPROVED** [review]
New links to web and release sites tested. Also checked that VERSIONINFO shown by EXE's show the proper information. All is good.

Ready to merge on your thumbs up.

-Dale

**Review by DLLarson — APPROVED** [review]

**Comment by wsu-cb** [comment]
Can I infer that you can't think of anything else that should be done before a beta release?  If so, then I'm ready.

**Comment by DLLarson** [comment]
>Can I infer that you can't think of anything else that should be done before a beta release?

The only thing I really would like to see in the *final* release is functioning DPI awareness. I have the color picker nearly complete. I figured it was a good place to start my DPI adventure. I'm just having some weird behavior when docking/undocking. However, DPI work shouldn't have any impacts on the file formats.

So I think it's ready for some folks to try it out so I'll merge what you've done.

-Dale

**Pull request merged**
