### PR TITLE
convert Board Editor from MFC to wxWidgets

### PR DESCRIPTION
**Pull request by wsu-cb**
The MFC doc/view framework is not being replaced yet, but, other than that, convert as much as is feasible of VwEdtbrd from MFC to wxWidgets .

### CODE REVIEW

**Comment by DLLarson** [comment]
Hi Bill,

I see your PR. I'll dig it in earnest in a few days.

Thanks!

-Dale

**Comment by DLLarson** [comment]
Hi Bill,

I'm still getting through the code. I'm down to 5 files but those are large and contain many changes. This PR contains a tremendous amount of work. I can't wait to see it in action (I usually inspect the code before I run it. That way I know where I want to drop breakpoints in interesting code.)

-Dale

**Comment by DLLarson** [comment]
Hi Bill,

Code inspection is done. It took longer than I expected. There are lots of changes and yet nothing prompted a comment out of me. Next I'll be looking at the runtime operation. 

Sorry for the delays.

-Dale

**Review by DLLarson — APPROVED** [review]
Everything seems to be running fine. Of course all the graphics are tiny on my 4K monitor. There is some kind of scaling support in wxWidgets for HiDPI screens but it's not automatic. With the graphics parts of the code using all wxWidgets the code may be getting to the point where the HiDPI problem can be addressed.

I'll merge on your command.

**Comment by wsu-cb** [comment]
> I'll merge on your command.

Merge, please.  I have nothing to add here.

**Comment by DLLarson** [comment]
Done.

**Pull request merged**
